name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:
    - name: Download and Install Localtonet
      run: |
        curl -o osx-64.zip https://localtonet.com/download/localtonet-osx-64.zip
        unzip osx-64.zip
        sudo chmod +x localtonet

    - name: Enabling Remote Access and Setting Up User
      run: |
        # Creating the user account
        sudo dscl . -create /Users/curseofwitcher
        sudo dscl . -create /Users/curseofwitcher UserShell /bin/bash
        sudo dscl . -create /Users/curseofwitcher RealName "Curse of Witcher"
        sudo dscl . -create /Users/curseofwitcher UniqueID 1001
        sudo dscl . -create /Users/curseofwitcher PrimaryGroupID 80
        sudo dscl . -create /Users/curseofwitcher NFSHomeDirectory /Users/curseofwitcher
        sudo dscl . -passwd /Users/curseofwitcher Howsthejosh@149
        sudo createhomedir -c -u curseofwitcher > /dev/null
        sudo dscl . -append /Groups/admin GroupMembership curseofwitcher

        # Enable VNC
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes 
        echo "Howsthejosh@149" | sudo tee /Library/Preferences/com.apple.VNCSettings.txt
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate

    - name: Start Localtonet with Authentication
      run: |
        ./localtonet authtoken jraqLE0YS2Ncev4fdhXy85uCB1UJoTiKM  # Replace with your actual token
        ./localtonet tcp 5900 --region=in &

    - name: Log In Details To VNC Server
      run: |
         chmod +x login.sh
         bash login.sh

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
