name: RDP_Setup

on: [push]

jobs:
  create_user_and_setup_rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Create User and Configure
      run: |
        echo "Creating User and Setting it up"
        username=user
        password=root
        sudo useradd -m $username
        sudo adduser $username sudo
        echo "$username:$password" | sudo chpasswd
        sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
        echo "User created and configured with username $username and password $password"
    
    - name: Install RDP
      run: |
        echo "Installing RDP, this may take 4-5 minutes"
        sudo apt update
        sudo wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg --install chrome-remote-desktop_current_amd64.deb
        sudo apt install --assume-yes --fix-broken

    - name: Install Desktop Environment
      run: |
        echo "Installing Desktop Environment"
        sudo apt install --assume-yes xfce4 desktop-base xfce4-terminal
        sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
        sudo apt remove --assume-yes gnome-terminal
        sudo apt install --assume-yes xscreensaver
        sudo systemctl disable lightdm.service

    - name: Install Google Chrome
      run: |
        echo "Installing Google Chrome"
        sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg --install google-chrome-stable_current_amd64.deb
        sudo apt install --assume-yes --fix-broken

    - name: Finalize RDP Setup
      run: |
        echo "Finalizing RDP Setup"
        autostart=false
        username=user
        CRP="DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AVG7fiRIpd2yulKy1830-Xke50yPUnOOeeOR0ezzqZcglP1y3R9KIDQiMSUJanpJJekv6A" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)"
        Pin=123456

        if $autostart; then
          sudo mkdir -p /home/$username/.config/autostart
          link="https://colab.research.google.com/github/PradyumnaKrishna/Colab-Hacks/blob/master/Colab%20RDP/Colab%20RDP.ipynb"
          colab_autostart="[Desktop Entry]\nType=Application\nName=Colab\nExec=sh -c 'sensible-browser $link'\nIcon=\nComment=Open a predefined notebook at session signin.\nX-GNOME-Autostart-enabled=true"
          echo -e $colab_autostart | sudo tee /home/$username/.config/autostart/colab.desktop
          sudo chmod +x /home/$username/.config/autostart/colab.desktop
          sudo chown $username:$username /home/$username/.config
        fi

        sudo adduser $username chrome-remote-desktop
        if [[ ! -z "$CRP" ]]; then
          sudo su - $username -c "$CRP --pin=$Pin"
        else
          echo "Please enter authcode from the given link"
        fi
        sudo service chrome-remote-desktop start

        echo "Finished Successfully"
