name: Windows 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Localtonet
      run: Invoke-WebRequest https://localtonet.com/download/localtonet-win-64.zip -OutFile localtonet.zip
    
    - name: Extract Localtonet
      run: Expand-Archive localtonet.zip
    
    - name: Auth with Localtonet
      run: .\localtonet\localtonet.exe authtoken 0twFLbUc7AeMRqGP13X8B2OkKJCVYuaTxogHhDz4yfpNZ

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
    
    - name: Create Tunnel
      run: .\localtonet\localtonet.exe tcp 3389
