name: winrdp
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download 
      run: Invoke-WebRequest https://localxpose.io/download/LocalXpose_Windows.zip -OutFile localxpose.zip
    - name: Extract
      run: Expand-Archive localxpose.zip
    - name: Auth
      run: .\LocalXpose\localxpose.exe authtoken $Env:LOCALXPOSE_AUTH_TOKEN
      env:
        LOCALXPOSE_AUTH_TOKEN: ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\LocalXpose\localxpose.exe tcp 3389
