name: Setup RDP with CRP Secret

on: [push]

jobs:
  setup-rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-terminal chrome-remote-desktop

    - name: Create User and Configure
      run: |
        sudo useradd -m ${{ secrets.USERNAME }}
        echo "${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}" | sudo chpasswd
        sudo usermod -aG sudo ${{ secrets.USERNAME }}

    - name: Configure RDP
      run: |
        sudo systemctl start chrome-remote-desktop
        echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session
        sudo su - ${{ secrets.USERNAME }} -c "${{ secrets.CRP }} --pin=${{ secrets.PIN }}"

    - name: Finish Setup
      run: |
        sudo systemctl restart chrome-remote-desktop
        echo "RDP Setup Complete"
