name: Windows 10 RDP Setup

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Download Localtonet
        run: Invoke-WebRequest https://localtonet.com/download/localtonet-win-64.zip -OutFile localtonet.zip

      - name: Extract Localtonet
        run: Expand-Archive localtonet.zip -DestinationPath ./localtonet

      - name: Set Localtonet Auth Token
        run: .\localtonet\localtonet.exe authtoken $Env:LOCALTONET_AUTH_TOKEN
        env:
          LOCALTONET_AUTH_TOKEN: "4uSym0JBtVPHTN9ZY7soU8WzDdi6rafkL"  # Your provided token

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "adityaa" -Password (ConvertTo-SecureString -AsPlainText "googleisbest" -Force)

      - name: Start Localtonet RDP Tunnel
        run: .\localtonet\localtonet.exe tcp 3389

      - name: Display Localtonet URL
        run: .\localtonet\localtonet.exe list
