name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
      
    - name: Enable Remote Desktop Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      
    - name: Configure User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
      
    - name: Set Local User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)

    - name: Get Public IP Address
      id: get_ip
      run: |
        $publicIP = (Invoke-WebRequest -Uri "http://api.ipify.org").Content
        Write-Host "Public IP Address: $publicIP"
        echo "::set-output name=ip::$publicIP"

    - name: Output Access Instructions
      run: |
        echo "You can access your Windows machine using Remote Desktop."
        echo "Use the following details:"
        echo "IP Address: ${{ steps.get_ip.outputs.ip }}"
        echo "Username: runneradmin"
        echo "Password: @cyb3rking"
