name: macOS RDP Setup with Localtonet

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 9999

    steps:
      - name: Download Localtonet for macOS (ARM64)
        run: curl -L https://localtonet.com/download/localtonet-osx-arm64.zip -o localtonet.zip

      - name: Extract Localtonet
        run: unzip localtonet.zip -d ./localtonet

      - name: Install xRDP (to enable RDP on macOS)
        run: |
          brew install xrdp
          sudo brew services start xrdp
          sudo systemsetup -setremotelogin on
          # Create a new user with specified username and password
          sudo dscl . -create /Users/rdpuser
          sudo dscl . -create /Users/rdpuser UserShell /bin/bash
          sudo dscl . -create /Users/rdpuser RealName "RDP User"
          sudo dscl . -create /Users/rdpuser UniqueID 1001
          sudo dscl . -create /Users/rdpuser PrimaryGroupID 80
          sudo dscl . -create /Users/rdpuser NFSHomeDirectory /Users/rdpuser
          sudo dscl . -passwd /Users/rdpuser googleisbest  # Set your password here 
          sudo dscl . -append /Groups/admin GroupMembership rdpuser  # Give admin privileges

      - name: Set Localtonet Auth Token
        run: ./localtonet/localtonet authtoken $LOCALTONET_AUTH_TOKEN
        env:
          LOCALTONET_AUTH_TOKEN: "4uSym0JBtVPHTN9ZY7soU8WzDdi6rafkL"  # Your provided token

      - name: Start Localtonet RDP Tunnel
        run: ./localtonet/localtonet tcp 3389

      - name: Display Localtonet URL
        run: ./localtonet/localtonet list
