name: Setup RDP with Chrome Remote Desktop

on:
  push:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    env:
      CRP: "${{ secrets.CRP }}" 
      PIN: "${{ secrets.PIN }}"
      username: "${{ secrets.USERNAME }}"
      password: "${{ secrets.PASSWORD }}"

    steps:
      - name: Create User
        run: |
          echo "Creating User and Setting it up"
          sudo useradd -m $username
          echo "$username:$password" | sudo chpasswd
          sudo usermod -aG sudo $username
          
          # Change default shell from sh to bash
          sudo chsh -s /bin/bash $username

      - name: Install Chrome Remote Desktop and Desktop Environment
        run: |
          echo "Installing Chrome Remote Desktop and Desktop Environment"
          sudo apt update
          sudo apt install --assume-yes wget xfce4 desktop-base xfce4-terminal xscreensaver

          # Download and install Chrome Remote Desktop
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo dpkg --install chrome-remote-desktop_current_amd64.deb || sudo apt install --assume-yes --fix-broken

      - name: Install Google Chrome
        run: |
          echo "Installing Google Chrome"
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg --install google-chrome-stable_current_amd64.deb || sudo apt install --assume-yes --fix-broken

      - name: Configure Chrome Remote Desktop
        run: |
          echo "Configuring Chrome Remote Desktop"
          echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" | sudo tee /etc/chrome-remote-desktop-session
          
          # Disable lightdm service if it exists
          sudo systemctl disable lightdm.service || true

      - name: Start Chrome Remote Desktop Host
        run: |
          echo "Starting Chrome Remote Desktop"
          
          # Add user to chrome-remote-desktop group
          sudo adduser $username chrome-remote-desktop

          # Start the host with the provided PIN
          sudo -u $username bash -c "DISPLAY= /opt/google/chrome-remote-desktop/start-host --code=\"$CRP\" --redirect-url=\"https://remotedesktop.google.com/_/oauthredirect\" --name=$(hostname) --pin=$PIN"
          
          # Start the service
          sudo service chrome-remote-desktop start

      - name: Finalize Setup
        run: |
          echo "RDP setup completed. You can access it via Google Remote Desktop."
