name: Setup Chrome Remote Desktop

on: [push]

jobs:
  setup_remote_desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chrome Remote Desktop
        run: |
          sudo apt update
          sudo apt install --assume-yes wget tasksel
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt-get install --assume-yes ./chrome-remote-desktop_current_amd64.deb
          sudo tasksel install ubuntu-desktop
          echo "exec /etc/X11/Xsession /usr/bin/gnome-session" | sudo tee /etc/chrome-remote-desktop-session

      - name: Configure Chrome Remote Desktop Host
        run: |
          # Set your desired PIN here
          echo "YOUR_PIN_HERE" | sudo tee /etc/chrome-remote-desktop/pin

      - name: Start Chrome Remote Desktop Host
        env:
          DISPLAY: :0  # Set this to your display number if needed
        run: |
          /opt/google/chrome-remote-desktop/start-host --code="4/0AVG7fiSxUQyg6rYVvZmk-wk8jQDsFXOKCYpy01TwP-sLnpuBOjGlsBrp2VltBDF7ZpLKMQ" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
          --name=$(hostname)
