name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/openziti/zrok/releases/download/v0.4.41/zrok_0.4.41_windows_amd64.tar.gz -OutFile zrok.zip
    - name: Extract
      run: Expand-Archive zrok.zip
    - name: Auth
      run: .\zrok\zrok.exe auth qAAxE5HHSLcu
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
    - name: Create Tunnel
      run: .\zrok\zrok.exe tcp 3389
