name: MacOS RDP Setup with Localtonet

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 9999

    steps:
      - name: Install required dependencies
        run: brew install xrdp unzip curl

      - name: Download Localtonet for MacOS
        run: curl https://localtonet.com/download/localtonet-osx-64.zip -o localtonet-osx.zip

      - name: Extract Localtonet
        run: unzip localtonet-osx.zip -d ./localtonet

      - name: Enable RDP and Configure User Account
        run: |
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          sudo ufw allow 3389/tcp
          sudo sysadminctl -addUser adisaanj -password curseofwitcher -admin
          sudo dscl . -append /Groups/admin GroupMembership rdpuser

      - name: Set Localtonet Permissions
        run: chmod 777 ./localtonet/localtonet

      - name: Set Localtonet Auth Token
        run: ./localtonet/localtonet authtoken $LOCALTONET_AUTH_TOKEN
        env:
          LOCALTONET_AUTH_TOKEN: "hUmz60Crbw9eLF1TOAastky7RgYl45dn3"  # Your provided token

      - name: Start Localtonet RDP Tunnel
        run: ./localtonet/localtonet tcp 3389

      - name: Display Localtonet URL
        run: ./localtonet/localtonet list
