name: Setup Localtonet for RDP

on: 
  push:
    branches:
      - main

jobs:
  setup_localtonet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Download Localtonet
        run: |
          wget https://localtonet.com/download/localtonet-linux-x64.zip
          unzip localtonet-linux-x64.zip
          chmod +x ./localtonet

      - name: Set AuthToken
        run: |
          echo "4uSym0JBtVPHTN9ZY7soU8WzDdi6rafkL" > authtoken.txt
          ./localtonet authtoken $(cat authtoken.txt)

      - name: Start RDP Tunnel
        run: |
          ./localtonet tcp 3389
          
      - name: Get Public Address
        run: |
          ./localtonet list
